SELECT * FROM (
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)
) a
WHERE a.HOUR >= 9 AND a.HOUR < 20






# 
# 조건 : 9:00 - 20:00에 입양이 몇 건 발생했는지 
# hour 함수 사용 ex) HOUR(시간이 포함된 datetime) => 시간만 빼준다.
# FROM에 서브쿼리 넣는다. : from에 넣을 때는 꼭 별칭을 넣어주어야 한다.








-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS H, COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
# WHERE DATE_FORMAT(DATETIME,'%H') BETWEEN '09' AND '19'
# GROUP BY H
# ORDER BY H


# SELECT HOUR(DATETIME), COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
# WHERE DATE_FORMAT(DATETIME,'%H') BETWEEN '09' AND '19'
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR(DATETIME)












