-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME,'%H') BETWEEN '09' AND '19'
GROUP BY HOUR
ORDER BY HOUR


# SELECT HOUR(DATETIME), COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
# WHERE DATE_FORMAT(DATETIME,'%H') BETWEEN '09' AND '19'
# GROUP BY DATETIME
# ORDER BY HOUR(DATETIME)