-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS H, COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
# WHERE DATE_FORMAT(DATETIME,'%H') BETWEEN '09' AND '19'
# GROUP BY H
# ORDER BY H

# group by hour... why?? 
SELECT HOUR(DATETIME), COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME,'%H') BETWEEN '09' AND '19'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)